#!D:\SATRIO\PERKULIAHAN\KULIAH SEMESTER 5\UAS\PEMROGRAMAN PYTHON LANJUT\virtualuas\Scripts\python.exe
import pcsv
from jtutils import fix_broken_pipe

if __name__ == "__main__":
    fix_broken_pipe()
    pcsv.pcsv()
